### ISSUE TITLE
WMS preview not working on Geoportal

### ISSUE THREAD

**Issue by antjacques** [INSPIRE-MIF/helpdesk-geoportal#249]
Dear helpdesk,

During this morning's MIG-T, this question was asked about dataset previews:
![Image](https://github.com/user-attachments/assets/d3ada268-065e-46ca-8e98-b91645b62fb6)

Indeed, I've tested a few of our (Luxembourg) preview on geoportal along with the ones from other countries and so far I haven't found one working properly: I always get a grey image.

![Image](https://github.com/user-attachments/assets/232d593b-13f0-4ecf-9e64-7a2bd0adf634)

So I looked into the GetMap request link provided in that section, here is a use case (https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=lu&view=thematicOverview&theme=none&resourceId=F22B07FC-E961-4985-BB75-6A1548319C8A):

- EU request (_not working_): https://wms.inspire.geoportail.lu/geoserver/ad/ows?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&LAYERS=AD_Address&FORMAT=image/png&CRS=CRS:84&BBOX=0.31298834928668673,0.2791819019039101,0.5216472488111445,0.4653031698398502&HEIGHT=256&WIDTH=256&STYLES=
- Luxembourg request (_working_): https://wms.inspire.geoportail.lu/geoserver/ad/wms?service=WMS&version=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&STYLES&LAYERS=AD_Address&CRS=EPSG:3035&WIDTH=534&HEIGHT=769&BBOX=2915378.733206663,4001783.670628123,3032705.4782545357,4083225.2290439

I suppose that there is something wrong when building the request. When I take the EU request and replace CRS and BBOX by the ones in our request --> it works fine (here under).
https://wms.inspire.geoportail.lu/geoserver/ad/ows?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&LAYERS=AD_Address&FORMAT=image/png&CRS=EPSG:3035&WIDTH=534&HEIGHT=769&BBOX=2915378.733206663,4001783.670628123,3032705.4782545357,4083225.2290439&STYLES=

Looks like the extent you use in your own request isn't the right one, it's centered around 0-0 coordinates, so in the middle of the ocean. When replacing it by correct coordinates it works:
https://wms.inspire.geoportail.lu/geoserver/ad/ows?REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&LAYERS=AD_Address&FORMAT=image/png&CRS=CRS:84&BBOX=5.878784,49.527169,6.398232,49.683802&HEIGHT=256&WIDTH=256&STYLES=

I had the opportunity to check those previews last year and I got the same results back then. From our perspective, the issue lies on your side but we remain available to discuss this matter if needed.

Thanks for your help!

**Comment by jescriu** [comment]
Dear @antjacques,
Thank you for spotting. I assigned the analysis of this issue to our ICT team.

**Comment by jrc-inspire** [comment]
Dear @antjacques ,
the issue has been solved: now dataset preview is correctly shown.

**Comment by antjacques** [comment]
Dear @jrc-inspire 

What kind of modifications did you implement? From what I can see, the preview issue hasn't been solved. 
Example below (https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=lu&view=thematicOverview&theme=none&resourceId=fe18759a-29ee-48dd-836b-2ed853bad31f), the GetMap request are the same as they used to as well:

![Image](https://github.com/user-attachments/assets/c6f6cf85-15a5-47a3-a6bd-954596c444d7)

**Comment by jescriu** [comment]
@jrc-inspire - Could you please re-check?

**Comment by jrc-inspire** [comment]
Dear @antjacques ,
sorry, we corrected the preview in the main page but effectively there was still a problem with the preview in the collapse elements.
The problem was due to some changes in the JSON structure, introduced in the Geonetwork version 1.1.4, that produces the map and for this Angular didn't manage it. Now we added some checks that cover also this situation and everything is OK.

**Comment by antjacques** [comment]
Hello @jrc-inspire, I confirm that the preview is now displaying properly! Thanks for the fix.

Just a slight issue remaining in my opinion: when I click 'Copy to clipboard' --> the URL in there is still the old request with the wrong BBOX thus displaying nothing. Is there a way for you to fix this as well?

Best regards,

**Comment by antjacques** [comment]
Hello @jrc-inspire @jescriu 

I cannot reopen this issue so just checking if you've seen my last comment.

Best regards

**Comment by jescriu** [comment]
@jrc-inspire - Could you please take care of this?

**Comment by antjacques** [comment]
Hello @jrc-inspire, just a ping concerning my last comment about the wrong getmap link

**Comment by jrc-inspire** [comment]
Dear @antjacques ,
after some attempts of developing a proper solution to have this optional functionality running properly for all Member States' endpoints, it was decided to remove the 'Copy to Clipboard' button from the Geoportal. Do not hesitate to contact us if more information is needed.
